add_newline = false

format = """
â•­â”€ $directory $git_branch $git_status
â”‚  $nodejs $python $cmd_duration
â•°â”€ $character
"""

[directory]
style = "bold cyan"
truncation_length = 3
truncate_to_repo = false

[git_branch]
symbol = "ğŸŒ± "
style = "bold purple"

[git_status]
style = "bold yellow"
format = '([!$modified]($style) [?$untracked]($style) )'

[nodejs]
symbol = "â¬¢ "
style = "bold green"

[cmd_duration]
min_time = 500
format = "â± [$duration]($style)"

[character]
success_symbol = "[âœ](bold green)"
error_symbol = "[âœ—](bold red)"
